apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: teampassword
  name: teampassword
  namespace: teampassword
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30568
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: teampassword
  sessionAffinity: None
  type: LoadBalancer
