apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpm-pvc
  namespace: teampassword
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
