apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpm-pvc
  namespace: teampassword
spec:
  storageClassName: example-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
