apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: teampassword
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
               secretKeyRef: 
                key: ROOT_PASSWORD
                name: teampassword-mysql
            - name: MYSQL_USER
              value: tpm_user
            - name: MYSQL_PASSWORD
              value: tpm_password
            - name: MYSQL_DATABASE
              value: tpm_database
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: example-nfs
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
